### ISSUE TITLE
`#TODO`

### ISSUE THREAD

**Issue by NNBnh** [NNBnh/orml#1]
- [ ] Support [Mermaid](https://mermaid-js.github.io/mermaid) through [ORML's codes](https://github.com/NNBnh/orml#-22-codes).
- [ ] Design ORML to also can replace [Latex](https://www.latex-project.org).
  - [ ] Support Math like [Asciidoctor](https://docs.asciidoctor.org/asciidoc/latest/stem) or [Latex](https://www.caam.rice.edu/~heinken/latex/symbols.pdf) ([note](http://xahlee.info/cmaci/notation/TeX_pestilence.html)) through [ORML's codes](https://github.com/NNBnh/orml#-22-codes) maybe with [Mathjax](https://www.mathjax.org/).
- [ ] Take a look at [Chartjs](https://www.chartjs.org).
- [ ] Make [Emmet](https://docs.emmet.io/cheat-sheet) unnecessary or work with something like that easier.
- [ ] Scan [this Reddit's post](https://www.reddit.com/r/ProgrammingLanguages/comments/n9yxq0/on_semantic_markup_language_design_and_how_i/) for more ideas.
